version: '3'
services:
  zoo:
    image: zookeeper
    restart: always
    container_name: zk
    ports:
      - "2181:2181"
  db:
    build: ./db/
    container_name: db
    ports: 
      - "3306:3306"
